# Generated by Django 6.0.7 on 2026-08-06 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RCRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=9, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('offer', models.JSONField(blank=True, null=True)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('host_ice', models.JSONField(default=list)),
                ('viewer_ice', models.JSONField(default=list)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CSPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.CharField(max_length=8)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='pdf_tools.csroom')),
            ],
        ),
        migrations.CreateModel(
            name='CSFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=36)),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('from_peer', models.CharField(max_length=8)),
                ('ts', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pdf_tools.csroom')),
            ],
        ),
    ]
